name: Deploy to VPS with Docker Compose

on:
  push:
    branches:
      - main
    tags:
      - v*  # Trigger on versioned tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      # 3. Build and Push Docker Image to GHCR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${{ github.sha }}
          # Build the Docker image with both 'latest' and commit-specific tags
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .
          # Push both tags to the registry
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

      # 4. Copy docker-compose.yml to VPS
      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: ./docker-compose.yml
          target: /srv/wearloot-api/

      # 5. Deploy using docker-compose
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /srv/wearloot-api/
            
            # Authenticate to GHCR on the VPS
            echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Set environment variables for docker-compose
            echo "DOCKER_IMAGE=ghcr.io/${{ github.repository }}:latest" > .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            
            # Pull the latest Docker image and restart the app
            docker-compose pull
            docker-compose up -d
